const userReduxTypes = {
  ADD_NATIVE_LANG: 'ADD_NATIVE_LANG',
  ADD_LEARNED_LANG: 'ADD_LEARNED_LANG',
  ADD_LEVEL: 'ADD_LEVEL',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  SET_ERRORS: 'SET_ERRORS',
  RESET_ERRORSSTATE_FORMS: 'RESET_ERRORSSTATE_FORMS',
  SET_ID_USER: 'SET_ID_USER',
  SET_USER_INFO: 'SET_USER_INFO',
  USER_TRACK_TRANSPARENCY:'USER_TRACK_TRANSPARENCY',
  USER_EURO_CONCENT:'USER_EURO_CONCENT'
};

export default userReduxTypes;
