export const alphabets = [
  'أبتثجحخدذرزسشصضطظعغفقكلمنهوي',
  'abcdefghijklmnopqrstuvwxyz',
  'abcdefghijklmnopqrstuvwxyz',
  'abcdefghijklmnopqrstuvwxyz',
  'abcdefghijklmnopqrstuvwxyz',
  'abcdefghijklmnopqrstuvwxyz',
  'abcdefghijklmnopqrstuvwxyz',
];
export const languages = [
  // Arabic
  {
    home: {
      week: 'أسبوع',
      day: 'يوم',
      discover: 'اكتشاف',
      practice: 'ممارسة',
      master: 'إتقان',
      review: 'مراجعة',
      weekly_test: 'اختبار أسبوعي',
      complete_all_the_days: 'أكمل كل أيام هذا الأسبوع لأداء الاختبار الأسبوعي',
      test: 'اختبار',
      today: 'اليوم',
      add: 'إضافة',
      profile: 'حسابي',
      premium: 'مميز',
    },
    custom: {
      add_custom_word: 'اظف كلمة خاصة',
      add_an_example: 'اظف مثال للكلمة',
      add_image: 'اظف صورة',
      add_at_least: 'اظف على الأقل 6 كلمات لحقيبتك الخاصة لبدأ الدرس',
    },
    start: 'ابدأ',
    finished: 'انتهى',
    continue: 'واصل',
    profile: {
      profile: 'حسابي',
      streaks: 'الشرائط',
      words: 'الكلمات',
      level: 'المستوى',
      contact_us: 'اتصل بنا',
      rate_us: 'قيمنا',
    },
    settings: {
      settings: 'اعدادات',
      uiLanguage: 'لغة الواجهة',
      logout: 'تسجيل الخروج',
      levels: ['مبتدأ', 'متوسط', 'جيد', 'متقدم'],
      languages: [
        'العربية',
        'الإنجليزية',
        'الفرنسية',
        'الألمانية',
        'الإيطالية',
        'الإسبانية',
        'البرتغالية',
      ],
      confirm: 'تأكيد',
    },
    month: [
      'جانفي',
      'فيفري',
      'مارس',
      'افريل',
      'ماي',
      'جوان',
      'جويلية',
      'اوت',
      'سبتمبر',
      'اكتوبر',
      'نوفمبر',
      'ديسمبر',
    ],
    startingScreens: {
      myNativeLan: 'لغتي الأم هي',
      iWantToLearn: 'اريد تعلم',
      selectYourLevel: 'ما هو مستواك في',
    },
    retype: 'اعد تركيب الكلمة',
    placeHolder: 'أعد كتابة الكلمة',
    cards: 'ركب الكلمة',
    missedChar: 'اكمل الكلمة',
    findit: 'اختر ماذا يعني',
    rehide: 'أعد كتابة الكلمة',
    writing: 'أعد كتابة الكلمة',
    hearIt: 'ماذا تسمع',
    check: 'تحقق',
    next: 'التالي',
  },

  // English
  {
    home: {
      week: 'week',
      day: 'day',
      discover: 'discover',
      practice: 'practice',
      master: 'master',
      review: 'review',
      weekly_test: 'weekly test',
      complete_all_the_days:
        'complete all the days of this week to take the weekly test',
      test: 'test',
      today: 'today',
      add: 'add',
      profile: 'profile',
      premium: 'premium',
    },
    custom: {
      add_custom_word: 'Add a custom word',
      add_an_example: 'Add an example of the word',
      add_image: 'Add an image',
      add_at_least: 'Add at least 6 words to your bag to start the lesson',
    },
    start: 'start',
    finished: 'Finished',
    continue: 'Continue',
    profile: {
      profile: 'Profile',
      streaks: 'Streaks',
      words: 'Words',
      level: 'Level',
      contact_us: 'Contact us',
      rate_us: 'Rate Us',
    },
    settings: {
      settings: 'Settings',
      uiLanguage: 'UI language',
      logout: 'Logout',
      levels: ['Beginner', 'Elementary', 'Intermediate', 'Advanced'],
      languages: [
        'Arabic',
        'English',
        'French',
        'German',
        'Italian',
        'Spanish',
        'Portuguese',
      ],
      confirm: 'Confirm',
    },
    month: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    startingScreens: {
      myNativeLan: 'My native language is',
      iWantToLearn: 'I want to learn',
      selectYourLevel: 'Select your level in',
    },
    retype: 'Rebuild the word with cards',
    placeHolder: 'Rewrite the word',
    cards: 'build the word with cards',
    missedChar: 'Complete the word',
    findit: 'Choose what mean',
    rehide: 'Rewrite the word',
    writing: 'Rewrite the word',
    hearIt: 'what do you hear',
    check: 'check',
    next: 'next',
  },

  // French

  {
    home: {
      week: 'semaine',
      day: 'jour',
      discover: 'découvrir',
      practice: 'pratiquer',
      master: 'maîtriser',
      review: 'Réviser',
      weekly_test: 'test hebdomadaire',
      complete_all_the_days:
        'complétez tous les jours de cette semaine pour passer le test hebdomadaire',
      test: 'test',
      today: "aujourd'hui",
      add: 'ajouter',
      profile: 'profil',
      premium: 'premium',
    },
    custom: {
      add_custom_word: 'Ajouter un mot personnalisé',
      add_an_example: 'Ajouter un exemple pour le mot',
      add_image: 'Ajouter une image',
      add_at_least:
        'Ajoutez au moins 6 mots à votre liste pour commencer la leçon',
    },
    start: 'commencer',
    finished: 'terminé',
    continue: 'continuer',
    profile: {
      profile: 'Profil',
      streaks: 'Streaks',
      words: 'Mots',
      level: 'Niveau',
      contact_us: 'Contactez-nous',
      rate_us: 'Évaluez nous',
    },
    settings: {
      settings: 'Paramètres',
      uiLanguage: 'UI langue',
      logout: 'Se déconnecter',
      levels: ['Débutant', 'Élémentaire', 'Intermédiaire', 'Avancé'],
      languages: [
        'Arabe',
        'Anglais',
        'Français',
        'Allemand',
        'Italien',
        'Espagnol',
        'Portugais',
      ],
      confirm: 'Confirmer',
    },
    month: [
      'Janvier',
      'Février',
      'Mars',
      'Avril',
      'Mai',
      'Juin',
      'Juillet',
      'Août',
      'Septembre',
      'Octobre',
      'Novembre',
      'Décembre',
    ],
    startingScreens: {
      myNativeLan: "Ma langue d'origine est",
      iWantToLearn: 'je veux apprendre',
      selectYourLevel: 'Sélectionnez votre niveau en',
    },
    retype: 'Reconstruire le mot avec les cartes',
    placeHolder: 'réécrire le mot',
    cards: 'construire le mot',
    missedChar: 'compléter le mot',
    findit: 'choisir ce que cela signifie',
    rehide: 'réécrire le mot',
    writing: 'réécrire le mot',
    hearIt: "Qu'entends-tu",
    check: 'vérifier',
    next: 'suivant',
  },

  // German

  {
    home: {
      week: 'Woche',
      day: 'Tag',
      discover: 'entdecken',
      practice: 'Praxis',
      master: 'meistern',
      review: 'Überprüfung',
      weekly_test: 'wöchentlicher Test',
      complete_all_the_days:
        'Bearbeiten Sie alle Tage dieser Woche, um den wöchentlichen Test abzulegen',
      test: 'Test',
      today: 'heute',
      add: 'hinzufügen',
      profile: 'Profil',
      premium: 'Premium',
    },
    custom: {
      add_custom_word: 'Benutzerdefiniertes Wort hinzufügen',
      add_an_example: 'Beispiel für das Wort hinzufügen',
      add_image: 'Bild hinzufügen',
      add_at_least:
        'Fügen Sie Ihrer Tasche mindestens 6 Wörter hinzu, um mit der Lektion zu beginnen',
    },
    start: 'starten',
    finished: 'beendet',
    continue: 'fortsetzen',
    profile: {
      profile: 'Profil',
      streaks: 'Streaks',
      words: 'Wörter',
      level: 'Niveau',
      contact_us: 'Kontaktiere uns',
      rate_us: 'Bewerten Sie uns',
    },
    settings: {
      settings: 'Einstellungen',
      uiLanguage: 'UI Sprache',
      logout: 'Ausloggen',
      levels: ['Anfänger', 'Elementar', 'Dazwischenliegend', 'Fortschrittlich'],
      languages: [
        'Arabisch',
        'Englisch',
        'Französisch',
        'Deutsch',
        'Italienisch',
        'Spanisch',
        'Portugiesisch',
      ],
      confirm: 'Bestätigen',
    },
    month: [
      'Januar',
      'Februar',
      'Marsch',
      'April',
      'Mai',
      'Juni',
      'Juli',
      'August',
      'September',
      'Oktober',
      'November',
      'Dezember',
    ],
    startingScreens: {
      myNativeLan: 'Meine Muttersprache ist',
      iWantToLearn: 'ich will lernen',
      selectYourLevel: 'Wählen Sie Ihr Niveau in',
    },
    retype: 'Rekonstruieren Sie das Wort',
    placeHolder: 'Schreibe das Wort um',
    cards: 'das Wort bauen',
    missedChar: 'das Wort vervollständigen',
    findit: 'wählen, was es bedeutet',
    rehide: 'Schreibe das Wort um',
    writing: 'Schreibe das Wort um',
    hearIt: 'Was hörst du',
    check: 'prüfen',
    next: 'nächste',
  },

  // Italian

  {
    home: {
      week: 'settimana',
      day: 'giorno',
      discover: 'scoprire',
      practice: 'pratica',
      master: 'maestria',
      review: 'revisione',
      weekly_test: 'test settimanale',
      complete_all_the_days:
        'completa tutti i giorni di questa settimana per sostenere il test settimanale',
      test: 'test',
      today: 'oggi',
      add: 'aggiungere',
      profile: 'profilo',
      premium: 'premium',
    },
    custom: {
      add_custom_word: 'Aggiungi una parola personalizzata',
      add_an_example: 'Aggiungi un esempio della parola',
      add_image: "Aggiungi un'immagine",
      add_at_least:
        'Aggiungi almeno 6 parole al tuo vocabolario per iniziare la lezione',
    },
    start: 'cominciare',
    finished: 'finito',
    continue: 'continuare',
    profile: {
      profile: 'Profilo',
      streaks: 'Streaks',
      words: 'Parole',
      level: 'Livello',
      contact_us: 'Contattaci',
      rate_us: 'Valutaci',
    },
    settings: {
      settings: 'Impostazioni',
      uiLanguage: 'UI lingua',
      logout: 'Disconnettersi',
      levels: ['Principiante', 'Elementare', 'Intermedio', 'Avanzate'],
      languages: [
        'Arabo',
        'Inglese',
        'francese',
        'Tedesco',
        'Italiano',
        'Spagnolo',
        'portoghese',
      ],
      confirm: 'Confermare',
    },
    month: [
      'Gennaio',
      'Febbraio',
      'Marzo',
      'aprile',
      'Maggio',
      'Giugno',
      'Luglio',
      'agosto',
      'settembre',
      'ottobre',
      'novembre',
      'Dicembre',
    ],
    startingScreens: {
      myNativeLan: 'La mia lingua madre è',
      iWantToLearn: 'Voglio imparare',
      selectYourLevel: 'Seleziona il tuo livello in',
    },
    retype: 'Ricostruisci la parola con le carte',
    placeHolder: 'Riscrivi la parola',
    cards: 'costruire la parola',
    missedChar: 'completare la parola',
    findit: 'scegliere cosa significa',
    rehide: 'Riscrivi la parola',
    writing: 'Riscrivi la parola',
    hearIt: 'Cosa senti',
    check: 'verificare',
    next: 'prossimo',
  },

  // Spanish

  {
    home: {
      week: 'semana',
      day: 'día',
      discover: 'descubrir',
      practice: 'práctica',
      master: 'dominar',
      review: 'revisión',
      weekly_test: 'prueba semana',
      complete_all_the_days:
        'completa todos los días de esta semana para tomar la prueba semanal',
      test: 'prueba',
      today: 'hoy',
      add: 'agregar',
      profile: 'perfil',
      premium: 'premium',
    },
    custom: {
      add_custom_word: 'Agregar una palabra personalizada',
      add_an_example: 'Agregar un ejemplo de la palabra',
      add_image: 'Agregar una imagen',
      add_at_least:
        'Agrega al menos 6 palabras a tu lista para empezar la lección',
    },
    start: 'comenzar',
    finished: 'terminado',
    continue: 'continuar',
    profile: {
      profile: 'Perfil',
      streaks: 'Streaks',
      words: 'Palabras',
      level: 'Nivel',
      contact_us: 'Contacta con nosotros',
      rate_us: 'Nos califica',
    },
    settings: {
      settings: 'Ajustes',
      uiLanguage: 'UI idioma',
      logout: 'Cerrar sesión',
      levels: ['Principiante', 'Elemental', 'Intermedio', 'Avanzado'],
      languages: [
        'Arábica',
        'Inglés',
        'Francés',
        'Alemán',
        'Italiano',
        'Español',
        'Portugués',
      ],
      confirm: 'Confirmar',
    },
    month: [
      'Enero',
      'Febrero',
      'Marzo',
      'Abril',
      'Mayo',
      'Junio',
      'Julio',
      'Agosto',
      'Septiembre',
      'Octubre',
      'Noviembre',
      'Diciembre',
    ],
    startingScreens: {
      myNativeLan: 'Mi lengua nativa es',
      iWantToLearn: 'quiero aprender',
      selectYourLevel: 'Selecciona tu nivel en',
    },
    retype: 'Reconstruir la palabra',
    placeHolder: 'reescribe la palabra',
    cards: 'construir la palabra',
    missedChar: 'completar la palabra',
    findit: 'elegir lo que significa',
    rehide: 'reescribe la palabra',
    writing: 'reescribe la palabra',
    hearIt: 'Qué escuchas',
    check: 'chequear',
    next: 'próximo',
  },

  // Protugais

  {
    home: {
      week: 'semana',
      day: 'dia',
      discover: 'descobrir',
      practice: 'prática',
      master: 'dominar',
      review: 'revisão',
      weekly_test: 'teste semanal',
      complete_all_the_days:
        'complete todos os dias desta semana para fazer o teste semanal',
      test: 'teste',
      today: 'hoje',
      add: 'adicionar',
      profile: 'perfil',
      premium: 'premium',
    },
    custom: {
      add_custom_word: 'Adicionar uma palavra personalizada',
      add_an_example: 'Adicionar um exemplo da palavra',
      add_image: 'Adicionar uma imagem',
      add_at_least:
        ' Adicione pelo menos 6 palavras ao seu vocabulário para começar a lição',
    },
    start: 'começar',
    finished: 'terminado',
    continue: 'continuar',
    profile: {
      profile: 'Perfil',
      streaks: 'Streaks',
      words: 'Palavras',
      level: 'Nível',
      contact_us: 'Contate-nos',
      rate_us: 'Nos avalie',
    },
    settings: {
      settings: 'configurações',
      uiLanguage: 'UI linguagem',
      logout: 'Sair',
      levels: ['Principiante', 'Elementar', 'Intermediário', 'Avançado'],
      languages: [
        'árabe',
        'Inglês',
        'Francês',
        'Alemão',
        'Italiano',
        'Espanhol',
        'Português',
      ],
      confirm: 'confirme',
    },
    month: [
      'Janeiro',
      'Fevereiro',
      'Marchar',
      'abril',
      'Maio',
      'Junho',
      'Julho',
      'Agosto',
      'Setembro',
      'Outubro',
      'novembro',
      'dezembro',
    ],
    startingScreens: {
      myNativeLan: 'Minha língua nativa é',
      iWantToLearn: 'eu quero aprender',
      selectYourLevel: 'Selecione seu nível em',
    },
    retype: 'Reconstruir a palavra',
    placeHolder: 'Reescreva a palavra',
    cards: 'construir a palavra',
    missedChar: 'completar a palavra',
    findit: 'escolher o que significa',
    rehide: 'Reescreva a palavra',
    writing: 'Reescreva a palavra',
    hearIt: 'O que você ouve',
    check: 'verificar',
    next: 'próximo',
  },
];
