const loopReduxTypes = {
  RESET_LOOP: 'RESET_LOOP',
  SET_LOOP_STEP: 'SET_LOOP_STEP',
  SET_LOOP_ROAD: 'SET_LOOP_ROAD',
  UPDATE_LOOP_STATE: 'UPDATE_LOOP_STATE',
  RESET_LOOP_STATE: 'RESET_LOOP_STATE',
  UPDATE_DEFAULT_ROAD: 'UPDATE_DEFAULT_ROAD',
  CLEAR_DEFAULT_ROAD: 'CLEAR_DEFAULT_ROAD',
  UPDATE_CUSTOM_ROAD: 'UPDATE_CUSTOM_ROAD',
  UPDATE_REVIEW_ROAD: 'UPDATE_REVIEW_ROAD',
  UPDATE_DAILY_TEST_ROAD: 'UPDATE_DAILY_TEST_ROAD',
  UPDATE_WEEKLY_TEST_ROAD: 'UPDATE_WEEKLY_TEST_ROAD',
  UPDATE_LOOP_ROAD: 'UPDATE_LOOP_ROAD',
  RESET_LOOP_ROAD: 'RESET_LOOP_ROAD',
  RESET_REVIEW_BAG_ARRAY: 'RESET_REVIEW_BAG_ARRAY',
  ADD_TO_REVIEW_BAG_ARRAY: 'ADD_TO_REVIEW_BAG_ARRAY',
  REMOVE_FROM_REVIEW_BAG_ARRAY: 'REMOVE_FROM_REVIEW_BAG_ARRAY',
  RESET_CUSTOM_BAG_ARRAY: 'RESET_CUSTOM_BAG_ARRAY',
  ADD_TO_CUSTOM_BAG_ARRAY: 'ADD_TO_CUSTOM_BAG_ARRAY',
  REMOVE_FROM_CUSTOM_BAG_ARRAY: 'REMOVE_FROM_CUSTOM_BAG_ARRAY',
};

export default loopReduxTypes;
