const wordsTypes = {
  WORDS_LOADING: 'WORDS_LOADING',
  AUDIO_LOADING: 'AUDIO_LOADING',
  ADD_ALL_WORDS: 'ADD_ALL_WORDS',
  CLEAR_ALL_WORDS: 'CLEAR_ALL_WORDS',
  MODIF_ALL_WORDS: 'MODIF_ALL_WORDS',
};

export default wordsTypes;
