const userTypes = {
  USER_DATA_ADDED: 'USER_DATA_ADDED',
  REDUX_DATA_CLEARED: 'REDUX_DATA_CLEARED',
  ADD_TODAY_WORDSBAG: 'ADD_TODAY_WORDSBAG',
  CLEAR_TODAY_WORDSBAG: 'CLEAR_TODAY_WORDSBAG',
  UPDATE_CURRENT_WORD: 'UPDATE_CURRENT_WORD',
  MODIFY_DEFAULT_WORDS_BAG: 'MODIFY_DEFAULT_WORDS_BAG',
  ADD_SUBLIST: 'ADD_SUBLIST',
  MODIFY_SUB_LIST: 'MODIFY_SUB_LIST',
  UPDATE_IS_DEFAULT_DISCOVER: 'UPDATE_IS_DEFAULT_DISCOVER',
  UPDATE_IS_CUSTOM_DISCOVER: 'UPDATE_IS_CUSTOM_DISCOVER',
  UPDATE_STEP_OF_DEFAULT_WORDS_BAG: 'UPDATE_STEP_OF_DEFAULT_WORDS_BAG',
  RESET_DEFAULT_STEP: 'RESET_DEFAULT_STEP',
  RESET_IS_DEFAULT_DISCOVER: 'RESET_IS_DEFAULT_DISCOVER',
  MODIFY_DAYS_BAGS: 'MODIFY_DAYS_BAGS',
  CLEAR_DAYS_BAGS: 'CLEAR_DAYS_BAGS',
};

export default userTypes;
